; EKO.ASM - ECHO ASCII KEYBOARD CHARACTERS   VERSION 1.0.0
; COPYRIGHT (C) 2016 AQUILA62 AT GITHUB.COM

; THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
; MODIFY IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS
; PUBLISHED BY THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF
; THE LICENSE, OR (AT YOUR OPTION) ANY LATER VERSION.

; THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
; BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
; MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE
; GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.

; YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
; ALONG WITH THIS PROGRAM; IF NOT, WRITE TO:

   ; FREE SOFTWARE FOUNDATION, INC.
   ; 59 TEMPLE PLACE - SUITE 330
   ; BOSTON, MA 02111-1307, USA.

KCIN   EQU 0006H
KCOUT  EQU 0009H
   ORG 100H
LP:
   CALL CIN
   CPI 'Q'
   JZ EOJ
   CPI 01AH
   JZ EOJ
   CALL COUT
   JMP LP
EOJ:
   JMP 0H
   NOP
   NOP
   NOP
   NOP
CIN:
   PUSH B
   PUSH D
   LXI D,KCIN
   CALL IOS
   POP D
   POP B
   ; RETURNS CHARACTER IN REG A
   RET
COUT:
   PUSH B
   PUSH D
   PUSH H
   MOV C,A
   LXI D,KCOUT
   CALL IOS
   POP H
   POP D
   POP B
   RET
IOS:
   LHLD 01H
   DAD D
   PCHL
   END LP

